description: "A new and modern Discord bot with many features, clean and beautifully built from the ground up using the Sapphire Framework and Lavalink. Supports Discord's latest chat features!"
markdown: gfm
remote_theme: "dracula/gh-pages"
