version: '3.9'
services:
    kohana:
        container_name: kohana
        build: .
        restart: on-failure
        tty: true
        environment:
            - ENVIRONMENT="production"
        env_file:
            - .env
        # ports:
            # - 6969:6969
        volumes:
            - .:/usr/kohana
